# Generated by Django 5.0.1 on 2024-03-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_is_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.FloatField(),
        ),
    ]
