# Generated by Django 5.0.1 on 2024-02-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskmodel_tasktitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='taskDescription',
            field=models.CharField(max_length=100),
        ),
    ]
