# Generated by Django 5.0.1 on 2024-03-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='description',
            field=models.TextField(max_length=552),
        ),
    ]
